backend:
  name: git-gateway
  branch: master
  squash_merges: true
publish_mode: editorial_workflow
show_preview_links: true
local_backend: true
use_graphql: true
media_folder: static
public_folder: /images
site_url: "https://www.thenewdynamic.org/"
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: tool
    label: Tools
    label_singular: "Tool"
    description: >
      Tools Database
    folder: content/tool
    create: true
    extension: md
    slug: "{{slug}}"
    preview_path: "tool/{{slug}}"
    identifier_field: "title"
    editor:
      preview: true
    fields:
      - widget: string
        name: title
        label: Title
        required: true
        hint: The title of the post
      - widget: string
        name: description
        label: Description
        required: false
        hint: Keep it brief.
      - widget: datetime
        name: date
        label: Date
        required: true
      - label: Tool Type
        name: tools
        widget: select
        multiple: true
        options:
          - Bundler/Task Runner
          - Content Management
          - Helper
          - Hosting-Deployment
          - Interaction
          - Serverless
          - Static Site Generator
          - Theme
          - Course
      - label: Interaction Type
        name: interactions
        widget: select
        required: false
        multiple: true
        options:
          - forms
          - images-media
          - search
          - commerce
          - authentication
          - privacy-data
          - comments/discussion
      - label: License
        name: license
        widget: select
        required: false
        multiple: false
        options:
          - Commercial
          - Open Source
          - Hybrid
          - Other
      - label: Data Model
        widget: select
        name: data_model
        required: false
        hint: For CMS/Editing Tools only
        options:
          - API-based
          - Git-based
          - Database
          - Other
      - label: Language
        widget: select
        name: language
        required: false
        multiple: false
        options:
          - Javascript
          - Go
          - Node
          - Ruby
          - Rust
          - Python
          - PHP
          - ".Net"
          - Java

        # - label: Related Tools
        #   widget: relation
        #   required: false
        #   name: related_tools
        #   hint: For non-static site generators to relate to a specific SSG
        #   collection: tool
        #   multiple: true
        #   searchFields: ["title"]
        #   valueField: title
        #   displayFields: ["title"]
      - label: "Links"
        name: "urls"
        widget: "object"
        collapsed: true
        required: false
        fields:
          - {
              label: "website",
              required: false,
              name: "website",
              widget: "string",
            }
          - {
              label: "twitter",
              required: false,
              name: "twitter",
              widget: "string",
            }
          - {
              label: "github",
              required: false,
              name: "github",
              widget: "string",
            }
      - label: "Resources"
        name: "resources"
        label_singular: "Resource"
        widget: "list"
        required: false
        fields:
          - { label: name, name: name, widget: string }
          - { label: URL, name: url, widget: string }

      # - name: tags
      #   widget: relation
      #   multiple: true
      #   create: true
      #   required: false
      #   selectFrom:
      #     - collection: data
      #       valueField: languages.language
      - widget: markdown
        name: body
        label: Content
        required: false
        hint: Page content
  - name: data
    label: Data
    files:
      - label: "Languages"
        name: "languages"
        file: "data/languages.yaml"
        fields:
          - label: languages
            name: languages
            collapsed: false
            widget: list
            field: { label: name, name: language, widget: string }

      - label: "Services"
        name: "services"
        file: "data/services.yaml"
        fields:
          - label: services
            name: services
            collapsed: false
            widget: list
            field: { label: name, widget: string }
