backend:
  name: git-gateway
  branch: master
media_folder: static/images
public_folder: /images
publish_mode: editorial_workflow
site_url: "https://www.thenewdynamic.org/"
show_preview_links: true
collections:
  - name: tool
    label: Tools
    folder: content/tool
    create: true
    extension: md
    slug: "{{slug}}"
    preview_path: "tool/{{slug}}"
    editor:
      preview: true
    fields:
      - widget: string
        name: title
        label: Title
        required: true
        hint: The title of the post
      - widget: string
        name: description
        label: Description
        required: false
        hint: Keep it brief.
      - widget: date
        name: date
        label: Date
        required: true
      - label: "Tool Type"
        name: "tools"
        widget: "select"
        options:
          - Bundler/Task Runner
          - Content Management
          - Helper
          - Hosting-Deployment
          - Interaction
          - Serverless
          - Static Site Generator
          - Theme
          - Course
      - widget: markdown
        name: body
        label: Content
        required: false
        hint: Page content
