backend:
  name: git-gateway
  branch: master
  squash_merges: true
publish_mode: editorial_workflow
show_preview_links: true
local_backend: true
media_folder: static
public_folder: /images
site_url: "https://www.thenewdynamic.org/"

collections:
  - name: tool
    label: Tools
    folder: content/tool
    create: true
    extension: md
    slug: "{{slug}}"
    preview_path: "tool/{{slug}}"
    editor:
      preview: true
    fields:
      - widget: string
        name: title
        label: Title
        required: true
        hint: The title of the post
      - widget: string
        name: description
        label: Description
        required: false
        hint: Keep it brief.
      - widget: datetime
        name: date
        label: Date
        required: true
      - label: Tool Type
        name: tools
        widget: select
        multiple: true
        options:
          - Bundler/Task Runner
          - Content Management
          - Helper
          - Hosting-Deployment
          - Interaction
          - Serverless
          - Static Site Generator
          - Theme
          - Course
      - label: Interaction Type
        name: interactions
        widget: select
        multiple: true
        options:
          - forms
          - images-media
          - search
          - commerce
          - authentication
          - privacy-data
          - comments/discussion
      - label: License
        name: license
        widget: select
        multiple: false
        options:
          - Commercial
          - Open Source
          - Hybrid
          - Other
      - label: Data Model
        widget: select
        name: data_model
        hint: For CMS/Editing Tools only
        options:
          - API-based
          - Git-based
          - Database
          - Other
      # - widget: relationship
      #   name: language
      #   label: Language
      #   collection: data.languages
      #   searchFields: ["languages"]
      #   valueField: "languages"

      - widget: markdown
        name: body
        label: Content
        required: false
        hint: Page content

  - name: data
    label: data
    files:
      - label: "Languages"
        name: "languages"
        file: "data/languages.yaml"
        fields:
          - label: "languages"
            collapsed: false
            name: "languages"
            widget: "list"
      - label: "services"
        name: "services"
        file: "data/services.yaml"
        fields:
          - label: "services"
            collapsed: false
            name: "services"
            widget: "list"
