# Config Base
# This is where root config key goes.
# ###################################
title: 'the New Dynamic'
baseURL: 'https://www.thenewdynamic.org'
DefaultContentLanguage: en
Paginate: 300
enableRobotsTXT: true
disableAliases: true
languageCode: en-us
# If project needs to build future: 
# buildFuture: true

# Some bugs related to 404 template https://github.com/gohugoio/hugo/issues/7603
disableKinds:
  - '404'
# googleAnalytics: UA-PROPERTY_ID
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

taxonomies:
  headless-cms: headless-CMS
  language: language
  license: license
  related_tool: related_tools
  series: series
  tag: tags
  tools: tools
  interaction: interactions