outputFormats:
  HEADERS:
    baseName: _headers
    isPlainText: true
    mediatype: text/netlify
    notAlternative: true
  REDIR:
    baseName: _redirects
    isPlainText: true
    mediatype: text/netlify
    notAlternative: true
