description: Build Better Faster Websites with JAMstack tools and techniques
logo: ""
subtitle: Build Better Faster Websites
utm_medium: website
utm_source: thenewdynamic.org
image_url: https://thenewdynamic-org.imgix.net
fathom_id: FZDREAIY
seo:
  default_image: /images/tnd-logo-card.png
  jsonld: true
tnd_redirects:
  use_aliases: true
  rules:
    - origin: /tools-content-mgmt-git
      target: /?jamstack-tools%5BrefinementList%5D%5Btool_type%5D%5B0%5D=Content%20Management&jamstack-tools%5BrefinementList%5D%5Bdata_model%5D%5B0%5D=Git-based
