description: Build Better Faster Websites with JAMstack tools and techniques
logo: ""
subtitle: Build Better Faster Websites
utm_medium: website
utm_source: thenewdynamic.org
image_url: https://thenewdynamic-org.imgix.net
fathom_id: FZDREAIY
seo:
  default_image: /images/tnd-logo-card.png
  jsonld: true
tnd_redirects:
  use_aliases: true
  rules:
    - origin: /jamstack-tools-cms-git
      target: /?jamstack-tools%5BrefinementList%5D%5Btool_type%5D%5B0%5D=Content%20Management&jamstack-tools%5BrefinementList%5D%5Bdata_model%5D%5B0%5D=Git-based
    - origin: /jamstack-tools-cms-api
      target: /?jamstack-tools%5BrefinementList%5D%5Btool_type%5D%5B0%5D=Content%20Management&jamstack-tools%5BrefinementList%5D%5Bdata_model%5D%5B0%5D=API-based
    - origin: /jamstack-tools-interaction-commerce
      target: /?jamstack-tools%5BrefinementList%5D%5Btool_type%5D%5B0%5D=Interaction&jamstack-tools%5BrefinementList%5D%5Binteraction_type%5D%5B0%5D=commerce
    - origin: /jamstack-tools-ssg-opensource
      target: ?jamstack-tools%5BrefinementList%5D%5Btool_type%5D%5B0%5D=Static%20Site%20Generator&jamstack-tools%5BrefinementList%5D%5Blicense%5D%5B0%5D=Open%20Source
