# Site settings
sitename: "{static is} The New Dynamic"
email: budparr@gmail.com
tagline: "Static Site Generators and the Post-CMS paradigm"
description: "{static is} The New Dynamic is a site for news and resources for static site generators, such as Jekyll, following the post-CMS paradigm"
baseurl: ""
url: "http://www.thenewdynamic.com"
port: 3575

# Build settings
markdown: kramdown
#permalink: pretty
permalink: /:categories/:title/
production: true
username: thenewdynamic
addthis_id: ra-500704bf6eb0a4da
google_analytics_id: UA-30899180-4
default_image: icon-temp.jpg
bust_css_cache: true

sass:
    style: :compressed
    sass_dir: assets/css/_sass

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "page"
      authors: budparr

prose:
  rooturl: '_posts'
  siteurl: 'http://www.thenewdynamic.com'
  media: 'assets/img'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "text"
          value: "blog"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""