# Site settings
sitename: "{static is} The New Dynamic"
email: budparr@gmail.com
tagline: "Following the Post-CMS paradigm"
description: "{static is} The New Dynamic is a site for news and resources for static site generators, such as Jekyll, following the post-CMS paradigm"
baseurl: ""
url: "http://www.thenewdynamic.com"
port: 3575

# Build settings
markdown: kramdown
#permalink: pretty
permalink: /:categories/:title/
production: true
username: budparr
addthis_id: ra-500704bf6eb0a4da
google_analytics_id: UA-30899180-4
default_image: icon-temp.jpg
bust_css_cache: true

sass:
    style: :compressed
    sass_dir: assets/css/_sass

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "page"
      authors: budparr