# Site settings
title: "{static is} The New Dynamic"
email: budparr@gmail.com
description: "Following the Post-CMS paradigm"
baseurl: ""
url: "http://www.thenewdynamic.com/"
port: 3575

# Build settings
markdown: kramdown
#permalink: pretty
permalink: /:categories/:title/

username: budparr


sass:
    style: :compressed
    sass_dir: assets/css/_sass

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "page"