DefaultContentLanguage: en
MetaDataFormat: yaml
Paginate: 300
baseURL: 'https://www.thenewdynamic.org'
disableAliases: false
enableRobotsTXT: true
googleAnalytics: UA-30899180-6
languageCode: en-us
preserveTaxonomyNames: true
rssLimit: 20
themesDir: components
theme:
  - layouts-base
title: the New Dynamic
blackfriday:
  fractions: false
mediaTypes:
  text/netlify:
    delimiter: ''
    suffixes: ''
menu:
  main:
    - identifier: jobs
      name: Find a Developer
      url: /jobs/
      weight: 5
    - name: Videos
      url: /video/
      weight: 2
    - identifier: community
      name: Community
      url: /community/
      weight: 4
    - identifier: showcase
      name: Showcase
      url: /showcase/
      weight: 3
    - identifier: tools
      name: Tools Directory
      url: /tool/
      weight: 1
  tools:
    - identifier: content-management
      name: Content Management
      url: /tools/content-management/
      weight: 4
    - identifier: api-based
      name: API-based
      parent: content-management
      url: /tools/headless-cms-api-based/
      weight: 3
    - identifier: static-site-generator
      name: Static Site Generator
      url: /tools/static-site-generator/
      weight: 2
    - identifier: git-based
      name: Git-based
      parent: content-management
      url: /tools/headless-cms-git-based/
      weight: 1
    - identifier: helper
      name: Helper
      url: /tools/helper/
      weight: 9
    - identifier: hosting-deployment
      name: Hosting & Deployment
      url: /tools/hosting-deployment/
      weight: 8
    - identifier: interaction-front-end
      name: 'Interaction: Front-end'
      url: /tools/interaction-front-end/
      weight: 7
    - identifier: interaction-backend
      name: 'Interaction: Back-end'
      url: /tools/interaction-back-end/
      weight: 6
outputFormats:
  HEADERS:
    baseName: _headers
    isPlainText: true
    mediatype: text/netlify
    notAlternative: true
  REDIR:
    baseName: _redirects
    isPlainText: true
    mediatype: text/netlify
    notAlternative: true
outputs:
  home:
    - HTML
    - HEADERS
    - REDIR
    - JSON
params:
  background_color_class: bg-near-white
  body_classes: font-sans bg-near-white border-solid border-t-4 border-primary-color
  description: Build Better Faster Websites with JAMstack tools and techniques
  logo: ''
  subtitle: Build Better Faster Websites
  utm_medium: website
  utm_source: thenewdynamic.org
  dev:    
    fonts_path: static/assets/Fonts
    image_url: 'https://thenewdynamic-org.imgix.net'
  
related:
  includeNewer: true
  indices:
    - name: tool
      toLower: true
      weight: 100
    - name: related_tools
      toLower: true
      weight: 100
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
social:
  meetup: 'https://www.meetup.com/JAMstack-nyc/'
  slack: >-
    https://join.slack.com/t/thenewdynamic/shared_invite/enQtMjkwNjYwNTY0NjkxLWI1NDhlNjZkZjA5ZGJmODE1OThiMjkwN2ZkMzE1YjEwN2YwNWUxYTNjZTUxMGQ2MzU3NWQ0YmVjNGU1NTkxMDk
  twitter: thenewdynamic
  youtube: thenewdynamic
taxonomies:
  headless-cms: headless-CMS
  language: language
  license: license
  related_tool: related_tools
  series: series
  tag: tags
  tools: tools
