languageCode = "en-us"
title = "the New Dynamic"
baseURL = "https://thenewdynamic-org.netlify.com"
theme = "thenewdynamic-hugo-core-theme"
MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
#SectionPagesMenu = "main"

#SectionPagesMenu = "main"
Paginate = 300 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"


[[menu.main]]
  name = "Articles & Videos"
  weight = 1
  identifier = "articles"
  url = "/article/"

[[menu.main]]
  name = "Links"
  weight = 10
  identifier = "Links"
  url = "/Link/"

[[menu.main]]
  name = "Tools Database"
  weight = 5
  identifier = "tools"
  url = "/tool/"

[[menu.main]]
  name = "Showcase"
  weight = 10
  identifier = "showcase"
  url = "/showcase/"

# [[menu.main]]
#   name = "Videos"
#   weight = 20
#   identifier = "videos"
#   url = "/videos/"

[[menu.main]]
  name = "Events"
  weight = 25
  identifier = "events"
  url = "/event/"

[[menu.main]]
  name = "Jobs"
  weight = 25
  identifier = "jobs"
  url = "/jobs/"


[[menu.secondary]]
  name = "About"
  weight = 25
  identifier = "about"
  url = "/about/"

[[menu.secondary]]
  name = "Submit"
  weight = 25
  identifier = "submit"
  url = "/submit/"

[[menu.secondary]]
  name = "Privacy"
  weight = 25
  identifier = "privacy"
  url = "/privacy/"





[params]
  logo = ""
  subtitle = "Build Faster Better Websites"
  body_classes = "sans-serif"
  background_color_class = "bg-near-white"
  description = "Build Faster Better Websites with modern tools, services and techniques."
  meetup = "https://www.meetup.com/JAMstack-nyc/"
  twitter = "https://twitter.com/thenewdynamic"
  slack = "https://join.slack.com/thenewdynamic/shared_invite/MTk5NzMwNDExNzY3LTE0OTc2MTc5MzAtNWU0ODIzZDIwZg"


[taxonomies]
  tag = "tags"
  tool_type = "tools"
  series = "series"
