---
DefaultContentLanguage: en
MetaDataFormat: yaml
Paginate: 300
baseURL: "https://www.thenewdynamic.org"
enableRobotsTXT: true
googleAnalytics: ""
languageCode: en-us
theme: "hugo-base-layouts"
#layoutDir: src/layouts
disableAliases: false
mediaTypes:
  text/netlify:
    delimiter: ""
    suffix: ""
menu:
  main:
    # -
    #   identifier: articles
    #   name: "Articles & Videos"
    #   url: /article/
    #   weight: 1
    # -
    #   identifier: Links
    #   name: Links
    #   url: /links/
    #   weight: 10
    -
      identifier: tools
      name: "Tools Directory"
      url: /tool/
      weight: 5
    -
      identifier: community
      name: Community
      url: /community/
      weight: 20
    -
      identifier: showcase
      name: Showcase
      url: /showcase/
      weight: 10
    # -
    #   identifier: events
    #   name: Events
    #   url: /event/
    #   weight: 25
    -
      identifier: jobs
      name: Jobs
      url: /jobs/
      weight: 25
  secondary:
    -
      identifier: about
      name: About
      url: /about/
      weight: 25
    -
      identifier: submit
      name: Submit
      url: /submit/
      weight: 25
    -
      identifier: privacy
      name: Privacy
      url: /privacy/
      weight: 25
  tools:
    -
      identifier: content-management
      name: "Content Management"
      url: /tools/content-management/
    -
      identifier: git-based
      name: Headless/Git-based
      parent: content-management
      url: /headless-cms/git-based/
    -
      identifier: api-based
      name: Headless/API-based
      parent: content-management
      url: /headless-cms/api-based/
    -
      identifier: helper
      name: Helper
      url: /tools/helper/
    -
      identifier: hosting-deployment
      name: Hosting & Deployment
      url: /tools/hosting-deployment/
    -
      identifier: interaction
      name: Interaction
      url: /tools/interaction/
    -
      identifier: static-site-generator
      name: Static Site Generator
      url: /tools/static-site-generator/
    -
      identifier: theme
      name: Themes
      url: /tools/theme/

outputFormats:
  HEADERS:
    baseName: _headers
    isPlainText: true
    mediatype: text/netlify
    notAlternative: true
  REDIR:
    baseName: _redirects
    isPlainText: true
    mediatype: text/netlify
    notAlternative: true
outputs:
  home:
    - HTML
    - HEADERS
    - REDIR
    - JSON
params:
  dev:
    fonts_path: "static/dist/Fonts"
    css_path: "static/dist/css"
    js_path: "static/dist/js"
  background_color_class: bg-near-white
  body_classes: "font-sans bg-near-white border-solid border-t-4 border-primary-color"
  description: "Build Faster Better Websites with modern tools and techniques"
  logo: ""

  subtitle: "Build Faster Better Websites"
preserveTaxonomyNames: true
related:
  includeNewer: true
  indices:
    -
      name: tool
      toLower: true
      weight: 100
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
social:
  twitter: thenewdynamic
  meetup: "https://www.meetup.com/JAMstack-nyc/"
  slack: "http://em.getrevue.co/mpss/c/JwE/1EoYAA/t.2ev/jSaKaYSMSceVQJcvS_U60A/h2/pOX6dG0WOSaHZ2xGmd4gW0-2BrN1qYSXeUzlrtE6-2BVVHGW98kh-2F2-2BGFDjImF5dH0Y6xebMeCT9MNxDau7ub3YeLycsgNuvcNz-2FX3nLY-2FICMvLdhuiC8Y73BLlet89Qcp29-2BePlJKx7TM7lfKr8D7ySqHSks0vCpkw0cfKSr0B6nrR7tXySaTIuzI7qAUTFoUtv5BAhGQCSnOpXZ6uUub7Pfw-3D-3D"
taxonomies:
  series: series
  tag: tags
  tools: tools
  related_tool: related_tools
  headless-cms: "headless-CMS"
  license: license
  language: language
title: "the New Dynamic"
