DefaultContentLanguage = "en"
MetaDataFormat = "yaml"
Paginate = 300.0
baseURL = "https://www.thenewdynamic.org"
disableAliases = false
enableRobotsTXT = true
googleAnalytics = "UA-30899180-6"
languageCode = "en-us"
preserveTaxonomyNames = true
theme = "hugo-base-layouts"
title = "the New Dynamic"
rssLimit = 20
[blackfriday]
fractions = false
[mediaTypes."text/netlify"]
delimiter = ""
suffixes = ""
[[menu.main]]
identifier = "tools"
name = "Tools Directory"
url = "/tool/"
weight = 1.0
[[menu.main]]
identifier = "jobs"
name = "Find a Developer"
url = "/jobs/"
weight = 4.0
[[menu.main]]
identifier = "showcase"
name = "Showcase"
url = "/showcase/"
weight = 2.0
[[menu.main]]
identifier = "community"
name = "Community"
url = "/community/"
weight = 3.0
[[menu.tools]]
identifier = "static-site-generator"
name = "Static Site Generator"
url = "/tools/static-site-generator/"
weight = 1.0
[[menu.tools]]
identifier = "content-management"
name = "Content Management"
url = "/tools/content-management/"
weight = 2.0
[[menu.tools]]
identifier = "git-based"
name = "Git-based"
parent = "content-management"
url = "/tools/headless-cms-git-based/"
weight = 1.0
[[menu.tools]]
identifier = "api-based"
name = "API-based"
parent = "content-management"
url = "/tools/headless-cms-api-based/"
weight = 2.0
[[menu.tools]]
identifier = "interaction-backend"
name = "Interaction: Back-end"
url = "/tools/interaction-back-end/"
weight = 3.0
[[menu.tools]]
identifier = "interaction-front-end"
name = "Interaction: Front-end"
url = "/tools/interaction-front-end/"
weight = 4.0
[[menu.tools]]
identifier = "hosting-deployment"
name = "Hosting & Deployment"
url = "/tools/hosting-deployment/"
weight = 5.0
[[menu.tools]]
identifier = "helper"
name = "Helper"
url = "/tools/helper/"
weight = 6.0
[outputFormats.HEADERS]
baseName = "_headers"
isPlainText = true
mediatype = "text/netlify"
notAlternative = true
[outputFormats.REDIR]
baseName = "_redirects"
isPlainText = true
mediatype = "text/netlify"
notAlternative = true
[outputs]
home = ["HTML", "HEADERS", "REDIR", "JSON"]
[params]
background_color_class = "bg-near-white"
body_classes = "font-sans bg-near-white border-solid border-t-4 border-primary-color"
description = "Build Faster Better Websites with modern tools and techniques"
logo = ""
subtitle = "Build Faster Better Websites"
utm_medium = "website"
utm_source = "thenewdynamic.org"
[params.dev]
css_path = "static/assets/css"
fonts_path = "static/assets/Fonts"
image_url = "https://thenewdynamic-org.imgix.net"
js_path = "static/assets/js"
[related]
includeNewer = true
[[related.indices]]
name = "tool"
toLower = true
weight = 100.0
[[related.indices]]
name = "related_tools"
toLower = true
weight = 100.0
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
[social]
meetup = "https://www.meetup.com/JAMstack-nyc/"
slack = "https://join.slack.com/t/thenewdynamic/shared_invite/enQtMjkwNjYwNTY0NjkxLWI1NDhlNjZkZjA5ZGJmODE1OThiMjkwN2ZkMzE1YjEwN2YwNWUxYTNjZTUxMGQ2MzU3NWQ0YmVjNGU1NTkxMDk"
twitter = "thenewdynamic"
youtube = "/channel/UCIGy4_KqcaGvltWCLpMXWug"
[taxonomies]
headless-cms = "headless-CMS"
language = "language"
license = "license"
related_tool = "related_tools"
series = "series"
tag = "tags"
tools = "tools"
