[build]
publish = "public"
command = "hugo --gc --minify"
functions = "functions"

[context.production.environment]
GO_VERSION = "1.14"
HUGO_VERSION = "0.73.0"
NODE_VERSION="10.13.0"
HUGO_ENV = "production"

[context.deploy-preview.environment]
HUGO_VERSION = "0.73.0"
NODE_VERSION="10.13.0"
GO_VERSION = "1.14"
HUGO_ENV = "preview"

[context.branch-deploy.environment]
HUGO_VERSION = "0.73.0"
NODE_VERSION="10.13.0"
GO_VERSION = "1.14"
HUGO_ENV = "staging"

[context.deploy-preview]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_URL"

[[headers]]
for = "/*"

[headers.values]
Content-Security-Policy = "upgrade-insecure-requests"
Strict-Transport-Security = "max-age=15768000"
X-Xss-Protection = "1; mode=block"
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Feature-Policy = "camera 'none'; geolocation 'none'; microphone 'none'"
