[build]
  command = "hugo"
  publish = "public"

[context.development.environment]
  HUGO_VERSION = "0.29.0"
  HUGO_ENV = "development"

# https://www.netlify.com/docs/continuous-deployment/#deploy-contexts
# https://www.netlify.com/blog/2017/04/11/netlify-plus-hugo-0.20-and-beyond/
