[build]
publish = "public"
command = "hugo --minify -e cached"

[build.environment]
  GO_VERSION = "1.14"
  NODE_VERSION = "15.4.0"
  HUGO_VERSION = "0.83.1"
  TND_SITE_ID = "tnd-org"

[functions]
  directory = "functions"

[context.production]

[context.production.environment]
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --minify -e cached -D -b $DEPLOY_PRIME_URL"
[context.deploy-preview.environment]
HUGO_ENV = "staging"

[context.branch-deploy]
command = "hugo --minify -e cached -b $DEPLOY_URL"
[context.branch-deploy.environment]
HUGO_ENV = "staging"

[[headers]]
for = "/*"

[headers.values]
Content-Security-Policy = "upgrade-insecure-requests"
Strict-Transport-Security = "max-age=15768000"
X-Xss-Protection = "1; mode=block"
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Feature-Policy = "camera 'none'; geolocation 'none'; microphone 'none'"

[dev]
functions = "functions"