---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 
sections:
  content/video:
    default_front_matter_template: video
  content/tools:
    default_front_matter_template: tools
  content/showcase:
    default_front_matter_template: showcase
  content/link:
    default_front_matter_template: link
  content/event:
    default_front_matter_template: event
  content/article:
    default_front_matter_template: article
  content/profile:
    default_front_matter_template: profile
  content/tool:
    default_front_matter_template: tool-directory
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: "/uploads"
use_front_matter_path: false
file_template: ":filename:"
version: 0.42.1
