---
upload_path: "/static/images/"
frontmatter_file_url_template: "/images/"
body_file_url_template: "/images/"
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 
sections:
  tools:
    default_front_matter_template: tools
  tool:
    default_front_matter_template: tools
  event:
    default_front_matter_template: event
version: 0.31.1
