---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/about
  label: About
  create: all
  match: "**/*"
- type: directory
  path: content/article
  label: Article
  create: all
  match: "**/*"
- type: directory
  path: content/event
  label: Event
  create: all
  match: "**/*"
- type: directory
  path: content/link
  label: Link
  create: all
  match: "**/*"
  templates:
  - link
- type: directory
  path: content/showcase
  label: Showcase
  create: all
  match: "**/*"
  templates:
  - showcase
- type: directory
  path: content/tools
  label: Tools
  create: all
  match: "**/*"
  templates:
  - tools
- type: directory
  path: content/tool
  label: Tool
  create: all
  match: "**/*"
  templates:
  - tool
- type: directory
  path: content/community
  label: Community
  create: all
  match: "**/*"
- type: directory
  path: content/profile
  label: Profile
  create: all
  match: "**/*"
- type: directory
  path: content/video
  label: Video
  create: all
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: "/uploads"
use_front_matter_path: false
file_template: ":filename:"
version: 0.42.1
