---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 
sections:
- type: heading
  label: Main Content
- type: directory
  path: content/tool
  label: Tools Directory
  create: all
  match: "**/*"
  templates:
  - tool
- type: directory
  path: content/showcase
  label: Showcase
  create: all
  match: "**/*"
  templates:
  - showcase
- type: directory
  path: content/video
  label: Video
  create: all
  match: "**/*"
  templates:
  - video
- type: directory
  path: content/link
  label: Links
  create: all
  match: "**/*"
  templates:
  - link
- type: heading
  label: Secondary Section
- type: directory
  path: content/event
  label: Events
  create: all
  match: "**/*"
- type: directory
  path: content/article
  label: Articles
  create: all
  match: "**/*"
  templates:
  - article
- type: directory
  path: data
  label: Data
  create: none
  match: "**/*.{json,yaml,yml,toml}"
- type: heading
  label: Internal Content
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/about
  label: About
  create: all
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: "/uploads"
use_front_matter_path: false
file_template: ":filename:"
version: 0.42.1
