---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: ''
sections:
  profile:
    default_front_matter_template: profile
  video:
    default_front_matter_template: video
  tool:
    default_front_matter_template: tool-directory
  article:
    default_front_matter_template: article
  tools:
    default_front_matter_template: tools
  showcase:
    default_front_matter_template: showcase
  link:
    default_front_matter_template: link
  event:
    default_front_matter_template: event
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: "/uploads"
use_front_matter_path: false
file_template: ":filename:"
version: 0.38.1
