---
hide_body: false
fields:
- name: date
  label: Date
  type: datetime
  hidden: false
  default: 
- type: textarea
  name: description
  label: Description
- name: images
  label: Images
  type: text
  hidden: false
  default: ''
